name: Init Flutter Project

on:
  workflow_dispatch:

jobs:
  create-project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Create Flutter project
        run: flutter create .

      - name: Upload generated files
        uses: actions/upload-artifact@v4
        with:
          name: flutter-project
          path: .
          
